export const projects = [
  {
    name: "westhead",
    displayName: "Westhead",
    images: 8,
    hero: 5,
    desription: null,
    type: "houses",
  },
  {
    name: "markham-close",
    displayName: "Markham Close",
    images: 11,
    hero: 1,
    desription: null,
    type: "houses",
  },
  {
    name: "brennan",
    displayName: "Brennan",
    images: 14,
    hero: 13,
    desription: null,
    type: "houses",
  },
  {
    name: "patteson",
    displayName: "Patteson Ave",
    images: 4,
    hero: 0,
    desription: null,
    type: "apartments",
  },
  {
    name: "waterview",
    displayName: "Waterview",
    images: 4,
    hero: 3,
    desription: null,
    type: "subdivisions",
  },
  {
    name: "addison",
    displayName: "Addison Developments",
    images: 4,
    hero: 3,
    desription:
      "Addison is a master planned community located within Takanini, 30 minutes drive south of Auckland city centre and two kilometres north of the Papakura commercial district. Situated on approximately 80ha of land it will include around 1,500 homes with a range of different housing styles from modern terraced housing to tree-lined streets of substantial family homes. A strong design mandate combined with long term vision forms the cornerstone of Addison's master plan. With interconnecting parkways, strong community urban form and thoughtful design, where reserves and expansive parks take central stage, great emphasis has been placed on maintaining the quality of the neighbourhood well into the future.\n\nOur involvement with this project has been to aid in the master-planning of the neighbourhoods and then design and document all housing from stage 2 onwards, approximately 500 dwellings over the past 5 years.",
    type: "subdivisions",
  },
];
